### ISSUE TITLE
Add deploy workflow

### ISSUE THREAD

**Issue by pepelsbey** [pepelsbey/elevencast#1]
Something like

```yml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Key
      - name: Setup key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      # Build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # Deploy
      - name: Deploy
        run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . elevencast.dev:/var/www/elevencast.dev/html/
        working-directory: ./dist
```
